name: vehicle_management_system
description: A Flutter Vehicle Management System
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.15

flutter:
  uses-material-design: true